# Generated by Django 4.1.5 on 2023-01-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description_short', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Описание')),
                ('lng_coordinate', models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Долгота')),
                ('lat_coordinate', models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Широта')),
            ],
        ),
    ]
