# Generated by Django 4.1.5 on 2023-01-06 13:01

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('places', '0001_initial'), ('places', '0002_image'), ('places', '0003_alter_place_lat_coordinate_and_more'), ('places', '0004_image_position'), ('places', '0005_alter_image_position'), ('places', '0006_alter_image_image'), ('places', '0007_alter_image_options_alter_image_position'), ('places', '0008_alter_image_position'), ('places', '0009_alter_image_options'), ('places', '0010_alter_place_description_long'), ('places', '0011_alter_place_description_short')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description_short', models.TextField(verbose_name='Краткое описание')),
                ('description_long', tinymce.models.HTMLField(blank=True, verbose_name='Описание')),
                ('lng_coordinate', models.FloatField(verbose_name='Долгота')),
                ('lat_coordinate', models.FloatField(verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Место')),
                ('position', models.IntegerField(db_index=True, default=0, verbose_name='Позиция')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
