# Generated by Django 4.1.5 on 2023-01-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat_coordinate',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng_coordinate',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
