# Generated by Django 4.1.5 on 2023-01-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_lat_coordinate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(blank=True, default=1, verbose_name='Позиция'),
            preserve_default=False,
        ),
    ]
