# Generated by Django 4.1.5 on 2023-01-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(verbose_name='Позиция'),
        ),
    ]
