# Generated by Django 4.1.5 on 2023-01-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_place_options_alter_place_description_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lat_coordinate',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='lng_coordinate',
            new_name='lng',
        ),
    ]
